version: "3"

services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.tests
    volumes:
      - /app/WorkflowsCore/obj/
      - /app/WorkflowsCore/bin/
      - /app/WorkflowsCore.Tests/obj/
      - /app/WorkflowsCore.Tests/bin/
      - /root/.nuget/
      - ./:/app

  build:
    build:
      context: .
      dockerfile: ./Dockerfile.build
    volumes:
      - /app/WorkflowsCore/obj/
      - /app/WorkflowsCore/bin/
      - /root/.nuget/
      - ./:/app
