FROM microsoft/dotnet:2.0.0-sdk

VOLUME /app

WORKDIR /app/WorkflowsCore

ENTRYPOINT dotnet restore \
  && rm -rf bin/Release/* \
  && dotnet pack --configuration Release /maxcpucount \
  && mkdir -p ../dist \
  && cp bin/Release/*.nupkg ../dist/
